version: '3'

services:
  site:
    build: /
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
